### ISSUE TITLE
Question about what to be include in the Algorithm, Documentation and Unit test.

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G5#11]
Do I have to include the state vector, probabilities or the Q-sphere graphs in the Algorithm or the unit test part??

What are the important things to be included??

**Comment by s4il3sh** [comment]
Do you mean in the documentation? If so, explain what you did in the Python file. The Python file is the coding that you have done arithmetic operations for to run in the quantum computer.
