### ISSUE TITLE
Encoding input using qiskit

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G5#14]
Do you have any idea about encoding input in Quantam register? We( group G-3) are trying to do division operation, so at first we have to convert the numbers we want to divide to Quantam states. I think for any other operations also, we first have to encode input. Please let me know, how you encode input to perform your operation.

**Comment by WildJimmy** [comment]
I responded to this in another group's issue https://github.com/ubsuny/23-Homework1G4/issues/24 which is hopefully helpful
