### ISSUE TITLE
i cannot push file to github

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework1G5#16]

**Comment by s4il3sh** [comment]
can you screenshot the problem to make it more clear?

**Comment by Mosaddeq107** [comment]
@LinxuanHu First, download this file from VS code, then upload it from the GitHub repository.
I think you didn't enter your credentials for your GitHub repository into the VSCode. That's why it identifies you as an alien.

**Comment by Mosaddeq107** [comment]
First, fork this repository of group_5 (@ubsuny/hw1g5_cp23-1 ), then upload this file to your forked repository. After that, make a merge request so that maintainers (me or Prof. Tim) will accept your request and then your fill will be visible to this repository (@ubsuny/hw1g5_cp23-1 ).
