### ISSUE TITLE
Which operation should we select? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework1G5#3]
@LinxuanHu  Hi,
Which arithmetics operation could we select for your assignment? @ubsuny/hw1g4_cp23-1 (group-4) took **multiplication** and @ubsuny/hw1g2_cp23-1 (group-2) took addition, we can go for subtraction.

**Comment by LinxuanHu** [comment]
yeah, we can do sbtraction.

**Comment by Mosaddeq107** [comment]
We agreed to do subtraction
