### ISSUE TITLE
quantum computer simulator

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework1G5#48]
is there a quantum computer simulator we can use in classical computer

**Comment by Mosaddeq107** [comment]
Yes, there are a number of quantum computer simulators that can be used on classical computers. These simulators allow you to develop and test quantum algorithms without having access to a physical quantum computer.

Some popular quantum computer simulators include:

Qiskit: Qiskit is an open-source quantum computing framework that includes a simulator for quantum circuits.
Cirq: Cirq is another open-source quantum computing framework that includes a simulator for quantum circuits.
