### ISSUE TITLE
Commit messages in wrong format

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G5#69]
Your commit messages are in .md files. I believe that it is not a proper way to write commit message.

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework1G5/assets/143649458/a4f46ff0-8011-425f-a268-4389aac38b3f)

**Comment by Mosaddeq107** [comment]
Can you please tell me which md file contains that error? @reshnashrestha

**Comment by reshnashrestha** [comment]
Not files but the commit messages
