### ISSUE TITLE
which IDE do you use for python?

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework1G5#9]
pycharm, vs code, or something else?

**Comment by reshnashrestha** [comment]
I am thinking of using VS code.

**Comment by JustinJaniszewski** [comment]
I personally like using replit.com. Very user friendly, supports multiple coding languages, saves everything online, and can be downloaded to your computer if needed.

**Comment by AhmedCode99** [comment]
I am using google colab. It works fine!

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski Google Colab saves every time online as well. But people have different choices and preferences.

**Comment by Mosaddeq107** [comment]
> I am using google colab. It works fine!

I prefer this as well. @AhmedCode99

**Comment by s4il3sh** [comment]
I prefer using Jupyter Notebook.
